version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:\Users\acer\todo101\data:/data/db

  todo-backend:
    build: ./backend
    ports:
      - "15000:15000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    depends_on:
      - mongo

  todo-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
